name: Build HRMS Image

on:
  schedule:
    - cron: '45 20 * * *'      # 02:15 IST daily
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g. 15)'
        required: false
        default: '15'
      force_rebuild:
        description: 'Force rebuild even if no changes'
        required: false
        default: 'false'
        type: boolean

env:
  REGISTRY_USER: robinfk
  FRAPPE_VERSION: version-${{ github.event.inputs.version || '15' }}
  ERPNEXT_VERSION: version-${{ github.event.inputs.version || '15' }}
  PYTHON_VERSION: 3.10.12
  NODE_VERSION: 18.12.0

jobs:
  build:
    name: Build HRMS
    runs-on: ubuntu-latest
    services:
      registry:
        image: docker.io/registry:2
        ports:
          - 5000:5000
    
    steps:
      - name: Checkout frappe_docker
        uses: actions/checkout@v4
      
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      
      - name: Prepare custom apps.json
        run: |
          # Create or update apps.json for HRMS
          cat > apps.json <<EOF
          [
            {
              "url": "https://github.com/frappe/frappe",
              "branch": "${{ env.FRAPPE_VERSION }}"
            },
            {
              "url": "https://github.com/frappe/erpnext",
              "branch": "${{ env.ERPNEXT_VERSION }}"
            },
            {
              "url": "https://github.com/frappe/hrms",
              "branch": "${{ env.ERPNEXT_VERSION }}"
            },
            {
              "url": "https://github.com/shridarpatil/frappe_whatsapp",
              "branch": "master"
            },
            {
              "url": "https://github.com/frappe/lms",
              "branch": "main"
            },
            {
              "url": "https://github.com/frappe/helpdesk",
              "branch": "main"
            },
            {
              "url": "https://github.com/frappe/crm",
              "branch": "main"
            }
          ]
          EOF
          
          # Base64 encode apps.json for build arg
          APPS_JSON_B64=$(base64 -w0 apps.json)
          echo "APPS_JSON_B64=$APPS_JSON_B64" >> $GITHUB_ENV
          
          # Modify Containerfile to avoid interactive prompts
          if [ -f "images/custom/Containerfile" ]; then
            sed -i 's/bench init \${APP_INSTALL_ARGS}/bench init --yes \${APP_INSTALL_ARGS}/g' images/custom/Containerfile
            echo "Modified Containerfile to avoid interactive prompts"
          else
            echo "Warning: images/custom/Containerfile not found"
            find . -name "Containerfile" | sort
          fi
      
      - name: Create custom HRMS bake target
        run: |
          # Create a simple bake file for HRMS
          cat > hrms-bake.hcl <<EOF
          target "hrms" {
            context = "."
            dockerfile = "images/custom/Containerfile"
            platforms = ["linux/amd64", "linux/arm64"]
            
            args = {
              FRAPPE_PATH = "https://github.com/frappe/frappe"
              FRAPPE_BRANCH = "${{ env.FRAPPE_VERSION }}"
              PYTHON_VERSION = "${{ env.PYTHON_VERSION }}"
              NODE_VERSION = "${{ env.NODE_VERSION }}"
              APPS_JSON_BASE64 = "${{ env.APPS_JSON_B64 }}"
            }
            
            tags = [
              "${{ env.REGISTRY_USER }}/hrms:v${{ github.event.inputs.version || '15' }}",
              "${{ env.REGISTRY_USER }}/hrms:latest"
            ]
          }
          EOF
      
      - name: Build locally first
        uses: docker/bake-action@v6.6.0
        with:
          files: hrms-bake.hcl
          load: true
          set: |
            *.platform=linux/amd64
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Push to Docker Hub
        uses: docker/bake-action@v6.6.0
        with:
          files: hrms-bake.hcl
          push: true
      
      - name: Workflow summary
        run: |
          echo "🟢 Successfully built and pushed ${{ env.REGISTRY_USER }}/hrms:v${{ github.event.inputs.version || '15' }}"
          echo "🟢 Also tagged as ${{ env.REGISTRY_USER }}/hrms:latest"
